bundler_args: --without development
before_install: gem install bundler

gemfile:
  - Gemfile

language: ruby

rvm:
  - 2.1.5

before_script:
  - mysql -u root -e 'create database QuoraClone_test;'

before_install:
  - mysql -u root -e "create database IF NOT EXISTS test;" -uroot

services:
  - mysql

dist: trusty

sudo: required

addons:
  apt:
    packages:
    - mysql-server-5.5
    - mysql-client-core-5.5
    - mysql-client-5.5