
development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: QuoraClone_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: QuoraClone_test
  pool: 5
  username: root
  password:

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: QuoraClone_production
  pool: 5
  username: root
  password:
